### ISSUE TITLE
print doesn't work in any event handler

### ISSUE THREAD

**Issue by MaxDesiatov** [kateinoigakukun/JavaScriptKit#11]
While using `print` as a top-level invocation works, if you call `print` in any closure handler, such as `onclick`, `addEventListener` etc, `print` output is not redirected to `console.log`. Apparently, there isn't anything that reads from stdout and redirects to `console.log` at that point.

**Comment by kateinoigakukun** [comment]
Hmm, how do you redirect stdout? Could you try that way used in IntegratedTests?

```javascript
const wasmFs = new WasmFs();
// Output stdout and stderr to console
const originalWriteSync = wasmFs.fs.writeSync;
wasmFs.fs.writeSync = (fd, buffer, offset, length, position) => {
  const text = new TextDecoder("utf-8").decode(buffer);
  switch (fd) {
  case 1:
    console.log(text);
    break;
  case 2:
    console.error(text);
    break;
  }
  return originalWriteSync(fd, buffer, offset, length, position);
};
```

**Comment by MaxDesiatov** [comment]
This is great, thanks! Would you mind if I create a PR that adds this to [`index.js` in the example](https://github.com/kateinoigakukun/JavaScriptKit/blob/master/Example/src/index.js)?

**Comment by kateinoigakukun** [comment]
Thanks. It would be helpful 🙏
