### ISSUE TITLE
Can't get properties from functions (Object.keys)

### ISSUE THREAD

**Issue by MaxDesiatov** [kateinoigakukun/JavaScriptKit#12]
This snippet crashes:

```swift
let object = JSObjectRef.global.Object.object!
```

as global `Object` is a function. This function has properties though, one of them being `Object.keys`. There is currently no way to access such property in JavaScriptKit, as this snippet crashes too:

```swift
let keys = JSObjectRef.global.Object.object!.keys!(anotherObject)
```

**Comment by kateinoigakukun** [comment]
`JSFunctionRef` is a `JSObjectRef`, so please access `global.Object` as a function.

e.g.

```swift
JSObjectRef.global.Object.function!.keys.function!(jsObject)
```

**Comment by MaxDesiatov** [comment]
Huh, I didn't know that `JSFunctionRef` supports dynamic members. Thanks for clarifying!
